### ISSUE TITLE
tag a release

### ISSUE THREAD

**Issue by mes5k** [gpertea/gclib#1]
Can you please tag a release of this software?  We'd like to user gffread and build it consistently with a tagged version of this lib.  Tags are much nicer than using commit hashes...

**Comment by tseemann** [comment]
@gpertea can you please make a release of this code?
We can't package `gffread` unless this is also released.

**Comment by mmokrejs** [comment]
@gpertea can you please make a release of this code?

**Comment by gpertea** [comment]
version tag updated and the release should be available in https://github.com/gpertea/gclib/releases

**Comment by mmokrejs** [comment]
Note to other readers/software package makers (don't ask for a tagged release, you don't need it):

https://github.com/gpertea/gclib/issues/2#issuecomment-400125651

https://github.com/gpertea/stringtie/issues/185#issuecomment-400128090
https://github.com/gpertea/stringtie/issues/186#issuecomment-400131844
https://github.com/gpertea/gffread/issues/26#issuecomment-400134376

https://github.com/Kingsford-Group/libgff/issues/1#issuecomment-399933609

**Comment by mes5k** [comment]
Thanks!
