### ISSUE TITLE
release of gclib 0.11.3 needed for gffread v0.11.6 

### ISSUE THREAD

**Issue by mr-c** [gpertea/gclib#5]
Specifically for `addPadding` and `removePadding` support.

This will allow us to update the packages in Debian; thanks!

**Comment by gpertea** [comment]
Done now - apologies for not keeping that tagged properly, thank you for reaching out to me about this, I really appreciate it.

**Comment by mr-c** [comment]
@gpertea No worries; thanks for the quick fix! I've submitted the new gclib package to Debian
